-- MySQL Script generated by MySQL Workbench
-- Thu Apr 21 10:29:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Table `vendor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendors` (
  `cnpj` INT NOT NULL,
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cnpj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ` purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `purchases` (
  `id` INT NOT NULL AUTO_INCREMENT, 
  `date` DATETIME NOT NULL,
  `price` DECIMAL NOT NULL,
  `quantity` INT NOT NULL,
  `vendor_cnpj` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_purchase_vendor`
    FOREIGN KEY (`vendor_cnpj`)
    REFERENCES `vendor` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `quantity` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `price` DECIMAL NOT NULL,
  `lot` INT NOT NULL,
  `id_vendor` INT NOT NULL,
  `manufacturing_date` DATETIME NOT NULL,
  `due_date` DATETIME NOT NULL,
  `purchase_id` INT NOT NULL,
  `vendor_cnpj` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_product_purchase`
    FOREIGN KEY (`purchase_id`)
    REFERENCES `purchase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_vendor`
    FOREIGN KEY (`vendor_cnpj`)
    REFERENCES `vendor` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `price` DECIMAL NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_sales_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
